### PR TITLE
update path to boot-classloader jar

### PR DESCRIPTION
**Pull request by ldenman**
When I run `make boot`, I get an about the standalone jar not existing. I updated the script to point to the correct location.

```
~/p/boot git:master $ make boot
rm -f boot
rm -rf resources/*
(cd boot-classloader; lein clean)
lein clean
mkdir -p resources
(cd boot-classloader; lein uberjar)
Compiling tailrecursion.boot-classloader.kahnsort
Compiling tailrecursion.boot-classloader
Created /home/me/phaser/boot/boot-classloader/target/uberjar/boot-classloader-0.1.0-SNAPSHOT.jar
Created /home/me/phaser/boot/boot-classloader/target/uberjar/boot-classloader-0.1.0-SNAPSHOT-standalone.jar
cp boot-classloader/target/boot-classloader*-standalone.jar resources/boot-classloader.jar
cp: cannot stat ‘boot-classloader/target/boot-classloader*-standalone.jar’: No such file or directory
Makefile:17: recipe for target 'build' failed
make: *** [build] Error 1
```

Things are looking better after I updated the Makefile:

```
~/p/boot git:master $ make boot                                                                                                                                                                                                            
rm -f boot
rm -rf resources/*
(cd boot-classloader; lein clean)
lein clean
mkdir -p resources
(cd boot-classloader; lein uberjar)
Created /home/me/phaser/boot/boot-classloader/target/uberjar/boot-classloader-0.1.0-SNAPSHOT.jar
Created /home/me/phaser/boot/boot-classloader/target/uberjar/boot-classloader-0.1.0-SNAPSHOT-standalone.jar
cp boot-classloader/target/uberjar/boot-classloader*-standalone.jar resources/boot-classloader.jar
lein uberjar
Compiling tailrecursion.boot.classlojure.core
Compiling tailrecursion.boot.loader
Compiling tailrecursion.boot.semver
Compiling tailrecursion.boot.strap
Created /home/me/phaser/boot/target/boot-1.0.5.jar
Created /home/me/phaser/boot/target/boot-1.0.5-standalone.jar
echo '#!/usr/bin/env bash' > boot
echo 'java $JVM_OPTS -jar $0 "$@"' >> boot
echo 'exit' >> boot
cat target/boot*-standalone.jar >> boot
chmod 0755 boot
*** Done. Created boot executable: ./boot ***
```

### CODE REVIEW

**Comment by alandipert** [comment]
Thanks @ldenman!  It looks like this is related to Leiningen - it appears that before 2.4.2, `lein` puts uberjars in `/target`.  Since 2.4.2, (released June 16) it puts them in `/target/uberjar`.

Would you mind updating this so that it either works for both `lein` behaviors or warns about the lein version?  Thanks!

**Comment by ldenman** [comment]
@alandipert I ended up changing my original commit. I changed the target-path in boot-classloader/project.clj to use the path specified in earlier versions of lein. I tested against 2.4.0 and 2.3.4.

**Comment by alandipert** [comment]
Thanks a million governor!

**Comment by samumbach** [comment]
:+1:

**Pull request merged**
